<?php

/**
 * @license LGPLv3, http://opensource.org/licenses/LGPL-3.0
 * @copyright Aimeos (aimeos.org), 2017
 * @package MW
 * @subpackage View
 */


namespace Aimeos\MW\View\Engine;


/**
 * Blade view engine implementation
 *
 * @package MW
 * @subpackage View
 */
class Blade implements Iface
{
	private $factory;


	/**
	 * Initializes the view object
	 *
	 * @param \Illuminate\View\Factory $factory Laravel view factory
	 */
	public function __construct( \Illuminate\View\Factory $factory )
	{
		$this->factory = $factory;
	}


	/**
	 * Renders the output based on the given template file name and the key/value pairs
	 *
	 * @param string $filename File name of the view template
	 * @param array $values Associative list of key/value pairs
	 * @return string Output generated by the template
	 * @throws \Aimeos\MW\View\Exception If the template isn't found
	 */
	public function render( $filename, array $values )
	{
		return $this->factory->file( $filename, $values )->render();
	}
}
